name: Attach HACS Release Asset

on:
  release:
    types: [published]

jobs:
  attach-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create homewhiz.zip
      run: cd custom_components && zip -r ../homewhiz.zip homewhiz/
    - name: Upload homewhiz.zip to release
      uses: softprops/action-gh-release@v2
      with:
        files: homewhiz.zip
