name: Checks manifest.json version matches tag

on:
  push:
    tags:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Read version from manifest.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' custom_components/homewhiz/manifest.json)
        echo "::set-output name=version::$VERSION"
    - name: Check version
      run: |
        TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        if [ "$TAG" != "${{ steps.get_version.outputs.version }}" ]; then
          echo "Version in manifest.json ${{ steps.get_version.outputs.version }} does not match tag $TAG"
          exit 1
        fi
